// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryxcfipnddnbktwupleh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5eGNmaXBuZGRuYmt0d3VwbGVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NTgzOTEsImV4cCI6MjA1NjEzNDM5MX0.trcPIz5EwT8NmggCmO-VNA6InZWRuKFagigeLA8bE5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);